//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodesDot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Career
    {
        public int Id { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string emailid { get; set; }
        public string phonenumber { get; set; }
        public string location { get; set; }
        public string linkedinprofile { get; set; }
        public string aboutyourself { get; set; }
        public string filename { get; set; }
        public byte[] filebinary { get; set; }
        public string filetype { get; set; }
    }
}
